[[headers]]
  for = "/asset/**/*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/asset/**/*.webp"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/asset/css/*.css"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/asset/js/*.js"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
